name: Test building the package
on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: Install uv
      run: sudo snap install --classic astral-uv
    - name: Build package
      run: uv build
