name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  test-package:
    uses: ./.github/workflows/test-package.yaml
  test-build:
    uses: ./.github/workflows/build-package.yaml
  check-src-changes:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    outputs:
      src_changed: ${{ steps.src-check.outputs.src_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - name: check if src files changed
        id: src-check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -Eq "^(src/|pyproject\\.toml|uv\\.lock)"; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi
  upload-package:
    needs:
      - test-package
      - test-build
      - check-src-changes
    if: |
      github.ref_name == 'main' &&
      needs.check-src-changes.outputs.src_changed == 'true'
    uses: ./.github/workflows/upload.yaml
    secrets: inherit
