name: Test the pylego package

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install letsencrypt/pebble
        working-directory: tests/integration
        run: |
          sudo snap install go --classic

          git clone https://github.com/letsencrypt/pebble.git
          cd pebble
          git reset ad9e5bba53b05abd18ee896434226db85a391285
          go install ./cmd/pebble
      - name: check version bump
        id: vbump
        uses: rgryta/Check-Bump@main
        with:
          method: 'toml'
          prefix: 'v'
      - name: install pylego
        run: |
          pip install --upgrade pip
          pip install ".[test]"

      - name: lint python
        run: |
          ruff check

      - name: test
        run: |
          export PATH=~/go/bin:$PATH
          pytest
