name: Test the pylego package

on:
  workflow_call:
    outputs:
      src_changed:
        description: "Indicates if source files have changed"
        value: ${{ jobs.test.outputs.src_changed }}

jobs:
  test:
    runs-on: ubuntu-22.04
    outputs:
      src_changed: ${{ steps.changed-files.outputs.src_changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install letsencrypt/pebble
        working-directory: tests/integration
        run: |
          sudo snap install go --classic

          git clone https://github.com/letsencrypt/pebble.git
          cd pebble
          git reset ad9e5bba53b05abd18ee896434226db85a391285
          go install ./cmd/pebble
      - name: install pylego
        run: |
          sudo snap install --classic astral-uv
          uv sync --dev 
      - name: lint python
        run: |
          uv run ruff check
      - name: test
        run: |
          export PATH=~/go/bin:$PATH
          uv run pytest
      - name: List changed files
        id: changed-files
        run: |
          files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' || true)
          echo "Files changed:"
          echo "$files"
          if echo "$files" | grep -q "^src/"; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: check version
        if: steps.changed-files.outputs.src_changed == 'true'
        id: vbump
        uses: rgryta/Check-Bump@main
        with:
          method: "toml"
          prefix: "v"

      - name: check version bump
        if: steps.changed-files.outputs.src_changed == 'true' && steps.vbump.outputs.bump == 'false'
        run: |
          echo "The project version was NOT bumped. version: ${{ steps.vbump.outputs.version }}"
          exit 1
