name: TiCS Static Analysis

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 3 am
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  analyze:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install --classic astral-uv
          uv venv
          uv pip install pytest pytest-cov pylint ruff
      - name: Generate code coverage
        run: |
          PYTHONPATH=src .venv/bin/python -m pytest tests/unit --cov=src --cov-report=xml:coverage.xml || true
      - name: Move results to necessary folder for TICS
        run: |
          mkdir -p cover
          mv coverage.xml cover/coverage.xml
      - name: Run TICS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: pylego
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true