name: Publish Python Package

on:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  upload-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          sudo snap install --classic astral-uv

      - name: Build package
        run: |
          uv build

      - name: Publish package to PyPI
        env:
          UV_PUBLISH_TOKEN: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          OUTPUT=$(uv publish) || true
          if echo "$OUTPUT" | grep -q "File already exists"; then
            echo "Package version already exists. Skipping further steps."
            exit 0
          fi
          echo "$OUTPUT"
